###### 도서 쇼핑몰 프로젝트 테이블 생성 SQL ######

### 생성 예상 테이블 ###
#1. 회원정보 테이블 SHOP_MEMBER
#2. 도서 카테고리 테이블 BOOK_CATEGORY
#3. 도서 정보 테이블 SHOP_BOOK
#4. 장바구니 테이블 SHOP_CART
#5. 구매 정보 테이블 SHOP_BUY

#회원정보 테이블 생성문
CREATE TABLE SHOP_MEMBER(
	MEM_EMAIL VARCHAR(50) PRIMARY 
	, MEM_PW VARCHAR(50) NOT NULL
	, MEM_NAME VARCHAR(30) NOT NULL
	, MEM_TEL VARCHAR(15) NOT NULL UNIQUE #'010-2222-2222'
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(100)
	, IS_USING VARCHAR(10) DEFAULT 'Y'  #'Y' : 사용중, 'N' : 사용 안 함
	, MEM_ROLE VARCHAR(20) DEFAULT 'USER' # USER: 회원, MANAGER : 쇼핑몰 운영자, ADMIN : 관리자
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);

#도서 카테고리 정보

CREATE TABLE BOOK_CATEGORY (
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE
);

SELECT *
FROM book_category;


SELECT *
FROM shop_book;
DROP TABLE BOOK_CATEGORY;
# 카테고리 기본 데이터 INSERT
INSERT INTO BOOK_CATEGORY VALUES(1,'IT/인터넷');
INSERT INTO BOOK_CATEGORY VALUES(2,'자기계발');
INSERT INTO BOOK_CATEGORY VALUES(3,'소설/에세이');

#도서 정보 테이블
CREATE TABLE SHOP_BOOK(
BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT
, BOOK_TITLE VARCHAR(30) NOT NULL
, AUTHOR VARCHAR(20) NOT NULL
, BOOK_PRICE INT NOT NULL
, BOOK_STOCK INT DEFAULT 10
, BOOK_INTRO VARCHAR(50)
, PUBLISH_DATE DATETIME #출판일
, CATE_NUM INT NOT NULL REFERENCES BOOK_CATEGORY (CATE_NUM)
);

SELECT *
FROM shop_member;

